name: kontribute
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.12+4
  http: ^0.12.2
  image_picker: ^0.6.7+17
  fluttertoast: ^7.0.4
  async: ^2.4.2
  multi_image_picker: ^4.7.13
  connectivity: ^0.4.2
  percent_indicator: ^2.1.7+2
  gradient_widgets: ^0.5.2
  flappy_search_bar: ^1.7.2
  flutter_speed_dial: ^1.0.9
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.3
  flutter_facebook_login: ^2.0.1
  firebase_messaging: ^6.0.12
  firebase_core: ^0.5.2
  flutter_twitter_login: ^1.0.1
  cached_network_image: ^2.0.0
  searchable_dropdown: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fontstyle/Poppins-Regular.ttf
      - asset: assets/fontstyle/Poppins-Bold.ttf
      - asset: assets/fontstyle/Poppins-Medium.ttf
      - asset: assets/fontstyle/Poppins-SemiBold.ttf

  assets:
    - assets/images/welcome1.png
    - assets/images/welcome2.png
    - assets/images/welcome3.png
    - assets/images/afterwelcome_bg.png
    - assets/images/forgot_bg.png
    - assets/images/languag_bg.png
    - assets/images/login_bg.png
    - assets/images/signup_bg.png
    - assets/images/btn.png
    - assets/images/facebook.png
    - assets/images/instagram.png
    - assets/images/snapchat.png
    - assets/images/telegram.png
    - assets/images/twitter.png
    - assets/images/gmail.png
    - assets/images/homelogo.png
    - assets/images/back.png
    - assets/images/camera.png
    - assets/images/click_radio.png
    - assets/images/not_click.png
    - assets/images/homeicon.png
    - assets/images/notificationicon.png
    - assets/images/profileicon.png
    - assets/images/settingicon.png
    - assets/images/walleticon.png
    - assets/images/person.png
    - assets/images/logo.png
    - assets/images/donation.png
    - assets/images/events.png
    - assets/images/invitation.png
    - assets/images/projectfunding.png
    - assets/images/sendreceivegift.png
    - assets/images/tickets.png
    - assets/images/appbar.png
    - assets/images/menu.png
    - assets/images/nav_bg.png
    - assets/images/userProfile.png
    - assets/images/nav_contactus.png
    - assets/images/nav_faq.png
    - assets/images/nav_home.png
    - assets/images/nav_invitation.png
    - assets/images/nav_mytranscaton.png
    - assets/images/nav_share.png
    - assets/images/nav_termsconditon.png
    - assets/images/banner1.png
    - assets/images/banner2.png
    - assets/images/addpost.png
    - assets/images/contct.png
    - assets/images/sendbutton.png
    - assets/images/edit.png
    - assets/images/editprofile.png
    - assets/images/wallet_bg.png
    - assets/images/walletbalace_bg.png
    - assets/images/walletlisticon.png
    - assets/images/createpost.png
    - assets/images/sendindividaul.png
    - assets/images/cameracreatenewgift.png
    - assets/images/csv.png
    - assets/images/pdf.png
    - assets/images/viewdetailsbg.png
    - assets/images/message.png
    - assets/images/heart.png
    - assets/images/banner5.png
    - assets/images/color_comment.png
    - assets/images/color_heart.png
    - assets/images/menudot.png
    - assets/images/events1.png
    - assets/images/events2.png
    - assets/images/chrimasevents.png
    - assets/images/play.png
    - assets/images/dollersign.png
    - assets/images/appicon.png
    - assets/images/appicon_circular.png
    - assets/images/cross.png
    - assets/images/qrcode.png
    - assets/images/wallet.png
    - assets/images/logo3.png
    - assets/images/underconstruction.png
    - assets/images/bg_img.png
    - assets/images/close.png
    - assets/images/categorymenu.png
    - assets/images/files.png
    - assets/images/search.png
    - assets/images/logout.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
